import type { HypeTier } from "./hype";

export const LINE_TIERS: Record<string, [HypeTier, string]> = {
  ".EXE": ["C", "Budget bundle"],
  ".SYS": ["A", ""],
  "5 Years // Beta Remastered": ["A", ""],
  "9 Lives": ["C", "Budget bundle"],
  "Abyssal": ["A", ""],
  "Aemondir": ["A", ""],
  "Aeris": ["S", "Recent standout, strong reception"],
  "Aero": ["C", "Budget bundle"],
  "Aerosol": ["C", "Budget bundle"],
  "Altitude": ["A", ""],
  "Aperture": ["A", ""],
  "Aquatica": ["C", "Budget bundle"],
  "Araxys": ["SS", "Bio cleaver hype"],
  "Araxys Bio Cleaver": ["SS", ""],
  "Arcane": ["A", ""],
  "Arcane Collector's Set": ["A", ""],
  "Aristocrat": ["B", ""],
  "Artisan": ["A", ""],
  "Astra": ["D", "Agent gear reward"],
  "ATLAS // CMD": ["A", ""],
  "Avalanche": ["B", ""],
  "Ayakashi": ["A", ""],
  "Belaflaire": ["C", "Budget bundle"],
  "Black.Market": ["A", ""],
  "Blackspyre": ["S", "Sharp dark line"],
  "Blackthorn": ["A", ""],
  "Blade of Serket": ["S", ""],
  "BlastX": ["S", "Meme-tier fun, huge fanbase"],
  "Blush": ["C", "Budget bundle"],
  "Bolt": ["A", ""],
  "Bound": ["A", ""],
  "Breach": ["D", "Agent gear reward"],
  "Brimstone": ["D", "Agent gear reward"],
  "Bubble Pop": ["A", ""],
  "Bubblegum Deathwish": ["A", ""],
  "Bulletbox": ["C", "Budget bundle"],
  "Bumble Brigade": ["C", "Budget bundle"],
  "Byteshift": ["A", ""],
  "Cavalier": ["B", ""],
  "Celestia": ["C", "Budget bundle"],
  "Celestial": ["A", ""],
  "Chamber": ["D", "Agent gear reward"],
  "Champions 2021": ["SSS", "Rare status symbol"],
  "Champions 2022": ["S", "Phantom year"],
  "Champions 2023": ["SS", "Butterfly knife carried it"],
  "Champions 2023 Butterfly Knife": ["SSS", ""],
  "Champions 2024": ["S", "Karambit year"],
  "Champions 2024 Karambit": ["SS", ""],
  "Champions 2025": ["S", "Latest Champions line"],
  "Chromedek": ["S", "Chrome finish fans"],
  "ChronoVoid": ["S", "Time-warp finisher"],
  "Chronovoid Sword": ["SS", ""],
  "Cloudweaver": ["C", "Budget bundle"],
  "Clove": ["D", "Agent gear reward"],
  "Coalition: Cobra": ["C", "Budget bundle"],
  "Combat Crafts": ["A", ""],
  "Comet": ["A", ""],
  "Composite": ["A", ""],
  "Convergence": ["C", "Budget bundle"],
  "Convex": ["C", ""],
  "Couture": ["C", "Budget bundle"],
  "Crash Out": ["C", "Budget bundle"],
  "Crimsonbeast": ["A", ""],
  "Cryostasis": ["A", ""],
  "Cypher": ["D", "Agent gear reward"],
  "CYRAX": ["A", ""],
  "Daydreams": ["A", ""],
  "Deadlock": ["D", "Agent gear reward"],
  "Depths": ["C", ""],
  "Digihex": ["C", "Budget bundle"],
  "Divergence": ["A", ""],
  "Divine Swine": ["C", "Budget bundle"],
  "Dolmir's Revenge": ["A", ""],
  "Doodle Buds": ["B", ""],
  "Doom Wing": ["C", "Budget bundle"],
  "Doombringer": ["A", ""],
  "Dragon Gate": ["C", "Budget bundle"],
  "Ego": ["A", ""],
  "Elderflame": ["SS", "The dragon guns"],
  "Elderflame Dagger": ["SS", ""],
  "Emberclad": ["A", ""],
  "Endeavour": ["C", ""],
  "Evori Dreamwings": ["SS", "Butterflies, gorgeous chromas"],
  "Evori Dreamwings Blades": ["SS", ""],
  "EX.O": ["A", ""],
  "Fade": ["D", "Agent gear reward"],
  "Fiber Optic": ["C", "Budget bundle"],
  "Forsaken": ["S", "Ritual blade, dark and loud"],
  "Forsaken Ritual Blade": ["SS", ""],
  "Fortune's Hand": ["A", ""],
  "Freehand": ["C", "Budget bundle"],
  "Frequency": ["C", "Budget bundle"],
  "Gaia's Vengeance": ["SSS", "Community favorite across every weapon"],
  "Gaia's Vengeance Katana": ["SSS", ""],
  "Galleria": ["C", ""],
  "Gekko": ["D", "Agent gear reward"],
  "Genesis": ["A", ""],
  "Glitchpop": ["SS", "Loud, loved, still sells"],
  "Glitchpop Dagger": ["SS", ""],
  "Goldwing": ["C", "Budget bundle"],
  "Gourmand": ["C", "Budget bundle"],
  "Gravitational Uranium Neuroblaster": ["A", ""],
  "Gridcrash": ["C", "Budget bundle"],
  "Guardrail": ["A", ""],
  "Haloform": ["C", "Budget bundle"],
  "Harbor": ["D", "Agent gear reward"],
  "Heartbreaker": ["C", "Budget bundle"],
  "Heartseeker": ["C", "Budget bundle"],
  "Heartstopper": ["A", ""],
  "Helix": ["A", ""],
  "Hi-DR0": ["A", ""],
  "Hieroscape": ["A", ""],
  "Hivemind": ["A", ""],
  "Holo Meridian": ["A", ""],
  "Holomoku": ["A", ""],
  "Horizon": ["B", ""],
  "Hue Shift": ["C", "Budget bundle"],
  "Hydrodip": ["C", "Budget bundle"],
  "Ignite": ["A", ""],
  "Immortalized": ["C", "Budget bundle"],
  "Imperium": ["SS", "Dragon-scale everything"],
  "Imperium Halberd": ["SS", ""],
  "Infantry": ["C", "Budget bundle"],
  "Infinity": ["B", ""],
  "Insidious": ["C", "Budget bundle"],
  "Intergrade": ["A", ""],
  "Interhelm": ["A", ""],
  "Intertwine": ["C", "Budget bundle"],
  "Ion": ["SS", "Clean, competitive favorite"],
  "Ion Energy Sword": ["SS", ""],
  "Iridian Thorn": ["A", ""],
  "Iso": ["D", "Agent gear reward"],
  "Jellybeam": ["A", ""],
  "Jett": ["D", "Agent gear reward"],
  "Jigsaw": ["C", "Budget bundle"],
  "K/TAC": ["A", ""],
  "KAY/O": ["D", "Agent gear reward"],
  "Keys to Elysium": ["A", ""],
  "Killjoy": ["D", "Agent gear reward"],
  "Kingdom": ["A", ""],
  "Kohaku & Matsuba": ["S", "Two-in-one animated line"],
  "Kuronami": ["SSS", "Instant classic"],
  "Kuronami Blade": ["SSS", ""],
  "Last Stop": ["C", "Budget bundle"],
  "Libretto": ["C", "Budget bundle"],
  "Lightwave": ["C", "Budget bundle"],
  "Luna": ["A", ""],
  "Luxe": ["A", ""],
  "Lycan's Bane": ["B", ""],
  "Magepunk": ["S", "Electric blade, beloved on Sheriff"],
  "Magepunk Electroblade": ["S", ""],
  "Miks": ["D", "Agent gear reward"],
  "Minima": ["B", "Clean and affordable"],
  "MK.VII Liberty": ["A", ""],
  "Monarch": ["C", "Budget bundle"],
  "Monstrocity": ["C", "Budget bundle"],
  "Montage": ["A", ""],
  "Moon Scout": ["C", "Budget bundle"],
  "Moondash": ["C", "Budget bundle"],
  "Mystbloom": ["SS", "Sakura vibes done right"],
  "Mystbloom Blade": ["SS", ""],
  "Nanobreak": ["C", "Budget bundle"],
  "Nanomight": ["A", ""],
  "Nebula": ["A", ""],
  "Neo Frontier": ["SS", "Bold western look"],
  "Neo Frontier Axe": ["S", ""],
  "Neon": ["D", "Agent gear reward"],
  "Neptune": ["S", "Aquarium guns"],
  "Nitro": ["C", ""],
  "NO LIMITS": ["A", ""],
  "Nocturnum": ["S", "Dark shadow theme"],
  "Nunca Olvidados": ["A", ""],
  "Omen": ["D", "Agent gear reward"],
  "Oni": ["SSS", "Iconic finisher and kill sound"],
  "Oni Claw": ["SSS", ""],
  "ORA by OneTap": ["A", ""],
  "Origin": ["S", "Original elegant design"],
  "Orion": ["A", ""],
  "Outpost": ["A", ""],
  "Overdrive": ["S", "Loud and flashy"],
  "Overlay": ["A", ""],
  "Paceline": ["A", ""],
  "Panoramic": ["C", "Budget bundle"],
  "Perch": ["C", "Budget bundle"],
  "Phaseguard": ["A", ""],
  "Phoenix": ["D", "Agent gear reward"],
  "Piedra del Sol": ["A", ""],
  "POLYfox": ["C", "Budget bundle"],
  "POLYfrog": ["C", "Budget bundle"],
  "Prelude to Chaos": ["S", "Big finisher, deep chromas"],
  "Prelude to Chaos Blade": ["S", ""],
  "Premiere Collision": ["C", "Budget bundle"],
  "Prime": ["SSS", "Timeless, sound design everyone knows"],
  "Prime Karambit": ["SSS", ""],
  "Prime//2.0": ["S", "Prime with a sharper edge"],
  "Primordium": ["A", ""],
  "Prism": ["A", ""],
  "Prism II": ["C", "Budget bundle"],
  "Prism III": ["B", ""],
  "Prism//Reloaded Outlaw": ["B", ""],
  "Protocol 781-A": ["S", "Talking gun"],
  "Radiant Crisis 001": ["A", "Comic book line"],
  "Radiant Entertainment System": ["S", "Arcade cabinet finisher"],
  "Radiant Entertainment System Fists": ["S", ""],
  "Raze": ["D", "Agent gear reward"],
  "RDVR": ["B", ""],
  "Reaver": ["SSS", "The classic pick, never left the meta"],
  "Reaver Butterfly Knife": ["SSS", ""],
  "Reaver Karambit": ["SSS", ""],
  "Recon": ["S", "Balisong and tactical look"],
  "Recon Balisong": ["S", ""],
  "Red Alert": ["C", "Budget bundle"],
  "Refractrix": ["C", "Budget bundle"],
  "Retrowave": ["C", "Budget bundle"],
  "Reverie": ["A", ""],
  "Reyna": ["D", "Agent gear reward"],
  "RGX 11z Pro": ["SSS", "Kill counter, bright chromas"],
  "RGX 11z Pro Blade": ["SSS", ""],
  "Rogue": ["A", ""],
  "Ruin": ["A", ""],
  "Ruination": ["S", "Sentinel sword, Viego vibes"],
  "Ruination Sword": ["S", ""],
  "Rune Stone": ["C", "Budget bundle"],
  "Rupture": ["C", "Budget bundle"],
  "Rush": ["C", ""],
  "Sage": ["D", "Agent gear reward"],
  "Sakura": ["B", ""],
  "Sandswept": ["A", ""],
  "Sarmad": ["A", ""],
  "Schema": ["C", "Budget bundle"],
  "Sensation": ["C", "Budget bundle"],
  "Sentinels of Light": ["S", "Relic sword and clean guns"],
  "Sentinels of Light Relic": ["SS", ""],
  "Serenity": ["C", "Budget bundle"],
  "Shellspire": ["A", ""],
  "Shimmer": ["C", "Budget bundle"],
  "Signature": ["C", "Budget bundle"],
  "Silhouette": ["C", "Budget bundle"],
  "SilkLeaf": ["A", ""],
  "Silvanus": ["B", ""],
  "Singularity": ["S", "Black-hole finisher"],
  "Singularity Knife": ["SS", ""],
  "Sky Reaper": ["A", ""],
  "Skye": ["D", "Agent gear reward"],
  "Smite": ["A", ""],
  "Snowfall": ["A", ""],
  "Solarex": ["A", ""],
  "Solarstride": ["A", ""],
  "Songsteel": ["A", ""],
  "Soulburst": ["C", "Budget bundle"],
  "Soulstrife": ["A", ""],
  "Sova": ["D", "Agent gear reward"],
  "Sovereign": ["S", "Gold-plated classic"],
  "Sovereign Sword": ["S", ""],
  "Space Piercer": ["C", "Budget bundle"],
  "Spectrum": ["SSS", "Zedd collab, music-reactive"],
  "Spectrum Waveform": ["SSS", ""],
  "Spellbound": ["C", "Budget bundle"],
  "Spitfire": ["C", "Budget bundle"],
  "SplashX": ["A", ""],
  "Spline": ["A", ""],
  "Starlit Odyssey": ["C", "Budget bundle"],
  "Storm Maw": ["A", ""],
  "Stormborne": ["C", "Budget bundle"],
  "Striker": ["A", ""],
  "Suit of Aeris": ["S", ""],
  "Superset": ["C", "Budget bundle"],
  "Surge": ["C", "Budget bundle"],
  "Switchback": ["A", ""],
  "Tacti-Guild": ["C", "Budget bundle"],
  "Tacti-Series": ["C", "Budget bundle"],
  "Tacti-Treat": ["C", "Budget bundle"],
  "Tactiplay": ["C", "Budget bundle"],
  "Task Force 809": ["A", ""],
  "Team Ace": ["B", ""],
  "Tejo": ["D", "Agent gear reward"],
  "Tethered Realms": ["A", ""],
  "Tigris": ["A", ""],
  "Tilde": ["A", ""],
  "Titanmail": ["A", ""],
  "Topotek": ["C", "Budget bundle"],
  "Torque": ["A", ""],
  "Transition": ["A", ""],
  "Undercity": ["S", "Grunge bundle people still ask for"],
  "Valiant Hero": ["S", "Bright anime hero line"],
  "VALORANT GO! Vol. 1": ["S", "Agent art, cult following"],
  "VALORANT GO! Vol. 2": ["A", ""],
  "VALORANT GO! Vol. 3": ["A", ""],
  "Varnish": ["C", "Budget bundle"],
  "VCT 2025 Season": ["B", "Esports team drop, one weapon"],
  "VCT 2026 Season": ["B", "Esports team drop, one weapon"],
  "VCT LOCK//IN": ["B", "Esports team drop, one weapon"],
  "VCT x 100T": ["B", "Esports team drop, one weapon"],
  "VCT x 2G": ["B", "Esports team drop, one weapon"],
  "VCT x AG": ["B", "Esports team drop, one weapon"],
  "VCT x APK": ["B", "Esports team drop, one weapon"],
  "VCT x BBL": ["B", "Esports team drop, one weapon"],
  "VCT x BLD": ["B", "Esports team drop, one weapon"],
  "VCT x BLG": ["B", "Esports team drop, one weapon"],
  "VCT x BOOM": ["B", "Esports team drop, one weapon"],
  "VCT x C9": ["B", "Esports team drop, one weapon"],
  "VCT x DFM": ["B", "Esports team drop, one weapon"],
  "VCT x DRG": ["B", "Esports team drop, one weapon"],
  "VCT x DRX": ["B", "Esports team drop, one weapon"],
  "VCT x EDG": ["B", "Esports team drop, one weapon"],
  "VCT x EG": ["B", "Esports team drop, one weapon"],
  "VCT x FNC": ["B", "Esports team drop, one weapon"],
  "VCT x FPX": ["B", "Esports team drop, one weapon"],
  "VCT x FS": ["B", "Esports team drop, one weapon"],
  "VCT x FUR": ["B", "Esports team drop, one weapon"],
  "VCT x FUT": ["B", "Esports team drop, one weapon"],
  "VCT x G2": ["B", "Esports team drop, one weapon"],
  "VCT x GE": ["B", "Esports team drop, one weapon"],
  "VCT x GEN": ["B", "Esports team drop, one weapon"],
  "VCT x GX": ["B", "Esports team drop, one weapon"],
  "VCT x JDG": ["B", "Esports team drop, one weapon"],
  "VCT x KC": ["B", "Esports team drop, one weapon"],
  "VCT x KOI": ["B", "Esports team drop, one weapon"],
  "VCT x KRÜ": ["B", "Esports team drop, one weapon"],
  "VCT x LEV": ["B", "Esports team drop, one weapon"],
  "VCT x LOUD": ["B", "Esports team drop, one weapon"],
  "VCT x M8": ["B", "Esports team drop, one weapon"],
  "VCT x MIBR": ["B", "Esports team drop, one weapon"],
  "VCT x NAVI": ["B", "Esports team drop, one weapon"],
  "VCT x NOVA": ["B", "Esports team drop, one weapon"],
  "VCT x NRG": ["B", "Esports team drop, one weapon"],
  "VCT x NS": ["B", "Esports team drop, one weapon"],
  "VCT x NV": ["B", "Esports team drop, one weapon"],
  "VCT x PCF": ["B", "Esports team drop, one weapon"],
  "VCT x PRX": ["B", "Esports team drop, one weapon"],
  "VCT x RRQ": ["B", "Esports team drop, one weapon"],
  "VCT x SEN": ["B", "Esports team drop, one weapon"],
  "VCT x T1": ["B", "Esports team drop, one weapon"],
  "VCT x TE": ["B", "Esports team drop, one weapon"],
  "VCT x TEC": ["B", "Esports team drop, one weapon"],
  "VCT x TH": ["B", "Esports team drop, one weapon"],
  "VCT x TL": ["B", "Esports team drop, one weapon"],
  "VCT x TLN": ["B", "Esports team drop, one weapon"],
  "VCT x TS": ["B", "Esports team drop, one weapon"],
  "VCT x TYL": ["B", "Esports team drop, one weapon"],
  "VCT x VIT": ["B", "Esports team drop, one weapon"],
  "VCT x VL": ["B", "Esports team drop, one weapon"],
  "VCT x WOL": ["B", "Esports team drop, one weapon"],
  "VCT x XLG": ["B", "Esports team drop, one weapon"],
  "VCT x ZETA": ["B", "Esports team drop, one weapon"],
  "Velocity": ["A", ""],
  "Venturi": ["A", ""],
  "Verdant Cafe": ["A", ""],
  "Veto": ["D", "Agent gear reward"],
  "Viper": ["D", "Agent gear reward"],
  "Vyse": ["D", "Agent gear reward"],
  "Wasteland": ["B", ""],
  "Wayfinder": ["D", "Agent gear reward"],
  "Waylay": ["D", "Agent gear reward"],
  "Winterwunderland": ["A", ""],
  "Wonderstallion": ["A", ""],
  "Xenohunter": ["S", "Predator inspired"],
  "Xenohunter Knife": ["S", ""],
  "XERØFANG": ["A", ""],
  "Yoonseul": ["C", "Budget bundle"],
  "Yoru": ["D", "Agent gear reward"],
};
